"""Regenerate the golden-value fixtures.

Usage (conda):

    conda env create -f tests/unit/golden/environment.yml   # first time only
    conda activate yq-golden
    python tests/unit/golden/generate.py

or with a plain virtualenv:

    python -m venv .venv && source .venv/bin/activate
    pip install -r tests/unit/golden/requirements.txt
    python tests/unit/golden/generate.py

Writes ``fixtures/_inputs.json`` (the signals) and ``fixtures/rms.json`` (what
NumPy computes for each). Commit both. The exact library versions used are
recorded inside each fixture under ``generatedBy``.
"""

import json
import platform
import sys
from pathlib import Path

import numpy as np

from inputs import build_signals

FIXTURES = Path(__file__).parent / "fixtures"


def versions():
    out = {"python": platform.python_version(), "numpy": np.__version__}
    try:
        import scipy

        out["scipy"] = scipy.__version__
    except ModuleNotFoundError:
        pass
    return out


def as_float32(x):
    """Round-trip through float32 -- the width the analyzer's deinterleave() uses.

    ``RMSAnalyzer`` never sees the raw float64 samples: the pipeline hands it a
    ``Float32Array``. Computing the reference over float32-rounded input keeps
    that quantisation out of the tolerance budget.
    """
    return np.asarray(x, np.float32).astype(np.float64)


def rms(x):
    return float(np.sqrt(np.mean(np.square(np.asarray(x, np.float64)))))


def dbfs(value, floor=-100.0):
    """dBFS relative to 1.0 -- matches src/analyzer/methods/stats.ts `dbfs`."""
    if value <= 0.0:
        return floor
    return float(max(floor, 20.0 * np.log10(value)))


def main():
    signals = build_signals()
    FIXTURES.mkdir(exist_ok=True)

    inputs_doc = {
        "generatedBy": versions(),
        "comment": "Generated by generate.py from inputs.py. Do not hand-edit.",
        "signals": {
            name: {
                "description": sig["description"],
                "fs": sig["fs"],
                "channels": [
                    np.asarray(c, np.float64).tolist() for c in sig["channels"]
                ],
            }
            for name, sig in signals.items()
        },
    }
    (FIXTURES / "_inputs.json").write_text(
        json.dumps(inputs_doc, indent=2) + "\n"
    )

    cases = []
    for name, sig in signals.items():
        f64 = [np.asarray(c, np.float64) for c in sig["channels"]]
        f32 = [as_float32(c) for c in sig["channels"]]
        cases.append(
            {
                "signal": name,
                # Reference for the pure `rms()` primitive (float64 in, float64 out).
                "expected": [rms(c) for c in f64],
                # Reference for RMSAnalyzer, whose input is float32 and whose
                # output is a Float32Array.
                "expectedFromFloat32": [rms(c) for c in f32],
                "expectedDbfs": [dbfs(rms(c)) for c in f32],
            }
        )

    rms_doc = {
        "generatedBy": versions(),
        "reference": "numpy: sqrt(mean(x**2)); dBFS = 20*log10(rms) relative to 1.0, floor -100",
        "cases": cases,
    }
    (FIXTURES / "rms.json").write_text(json.dumps(rms_doc, indent=2) + "\n")

    print(f"wrote {len(signals)} signals and {len(cases)} RMS cases")
    print("versions:", versions())
    return 0


if __name__ == "__main__":
    sys.exit(main())
